(function(){
 const D=window.BUSINESS_DATA,T=window.TRANSLATIONS; T.ar.servicesTitle='خدمات متكاملة لسيارتك'; T.en.servicesTitle='Complete services for your car'; T.ar.rateExperience='قيّم تجربتك على Google'; T.en.rateExperience='Rate your experience on Google'; let lang=localStorage.getItem('alEnjazLang')||'ar',reviewTimer=null,reviewIndex=0;
 const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
 function tr(k){return T[lang][k]??k} function serviceName(s){return lang==='ar'?s.ar:s.en} function serviceDesc(s){return lang==='ar'?s.descAr:s.descEn}
 function whatsappUrl(message){return `https://wa.me/${D.phone.replace(/\D/g,'')}?text=${encodeURIComponent(message)}`}
 function render(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$('#langToggle').textContent=lang==='ar'?'EN':'ع';$('#langToggle').setAttribute('aria-label',lang==='ar'?'Switch to English':'التبديل إلى العربية');$$('[data-i18n]').forEach(el=>el.innerHTML=tr(el.dataset.i18n));$$('[data-bind]').forEach(el=>{let k=el.dataset.bind;if(k==='nameAr')el.textContent=lang==='ar'?'الإنجاز':'AL ENJAZ';else if(k==='addressAr')el.textContent=lang==='ar'?D.address.fullAr:D.address.fullEn;else el.textContent=D[k]});
  const brandItems=D.brands.map(b=>`<div class="brand-chip"><img src="${b.logo}" alt="شعار ${b.name}" width="54" height="54" loading="lazy"><span><b>${b.name}</b>${b.verified?'':`<small>${tr('unverified')}</small>`}</span></div>`).join('');
  $('#brandList').innerHTML=`<div class="brand-marquee-track"><div class="brand-marquee-group">${brandItems}</div><div class="brand-marquee-group" aria-hidden="true">${brandItems}</div></div>`;
  $('#serviceList').innerHTML=D.services.map((s,i)=>`<article class="service-card reveal"><span>${String(i+1).padStart(2,'0')}</span><i aria-hidden="true"></i><h3>${serviceName(s)}</h3><p>${serviceDesc(s)}</p><a href="booking.html?service=${encodeURIComponent(s.id)}">${lang==='ar'?'احجز هذه الخدمة':'Book this service'} <b>↗</b></a></article>`).join('');
  $('#reviewTrack').innerHTML=D.reviews.map((r,i)=>`<article class="review-card"><div class="review-card-top"><span class="google-g" aria-hidden="true">G</span><span class="stars" aria-label="${r.rating} ${lang==='ar'?'نجوم':'stars'}">${'★'.repeat(r.rating)}</span><small>${lang==='ar'?r.dateAr:r.dateEn}</small></div><blockquote>“${lang==='ar'?r.textAr:r.textEn}”</blockquote><div class="review-author"><b>${r.name}</b><span>${lang==='ar'?'مراجعة Google':'Google review'}</span></div><span class="review-number">${String(i+1).padStart(2,'0')}</span></article>`).join('');
  $('#processList').innerHTML=tr('process').map((x,i)=>`<li class="reveal"><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></li>`).join('');
  $('#faqList').innerHTML=tr('faqs').map((x,i)=>`<article><button type="button" aria-expanded="false" aria-controls="faq-${i}"><span>${x[0]}</span><b>+</b></button><div id="faq-${i}" hidden><p>${x[1]}</p></div></article>`).join('');
  const keys=['sun','mon','tue','wed','thu','fri','sat'];$('#hoursList').innerHTML=keys.map((k,i)=>{let h=D.openingHours[k];return `<div><span>${tr('days')[i]}</span><b>${h.open?`${h.open} – ${h.close}`:(lang==='ar'?h.noteAr:h.noteEn)}</b></div>`}).join(''); bindDynamic(); setupReviewControls(); setupMotionDetails(); updateStatus(); observe();
 }
 function bindDynamic(){const wa=whatsappUrl(lang==='ar'?'السلام عليكم،\nأرغب بالاستفسار عن صيانة سيارتي.\n\nنوع السيارة:\nالموديل:\nسنة الصنع:\nالمشكلة:':'Hello,\nI would like to ask about servicing my car.\n\nMake:\nModel:\nYear:\nIssue:');$$('.js-whatsapp').forEach(a=>{a.href=wa;if(!D.whatsappEnabled)a.title=lang==='ar'?'استخدام واتساب يحتاج تأكيد المركز':'Workshop WhatsApp support requires confirmation'});$$('.js-phone').forEach(a=>a.href=`tel:${D.phone}`);$$('.js-maps').forEach(a=>a.href=D.googleMapsUrl);$$('.accordion button').forEach(b=>b.onclick=()=>{const expanded=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!expanded));b.querySelector('b').textContent=expanded?'+':'−';document.getElementById(b.getAttribute('aria-controls')).hidden=expanded})}
 function setupReviewControls(){const track=$('#reviewTrack');if(!track)return;const cards=$$('.review-card',track);clearTimeout(reviewTimer);reviewIndex=0;const show=index=>{if(!cards.length)return;reviewIndex=(index+cards.length)%cards.length;const cardBox=cards[reviewIndex].getBoundingClientRect(),trackBox=track.getBoundingClientRect();track.scrollBy({left:cardBox.left-trackBox.left,behavior:'smooth'})};const stop=()=>{clearTimeout(reviewTimer);reviewTimer=null};const schedule=()=>{stop();if(matchMedia('(prefers-reduced-motion: reduce)').matches||cards.length<2)return;const delay=3000+Math.random()*2000;reviewTimer=setTimeout(()=>{show(reviewIndex+1);schedule()},delay)};$('#reviewPrev').onclick=()=>{show(reviewIndex-1);schedule()};$('#reviewNext').onclick=()=>{show(reviewIndex+1);schedule()};track.addEventListener('mouseenter',stop);track.addEventListener('mouseleave',schedule);track.addEventListener('focusin',stop);track.addEventListener('focusout',schedule);track.addEventListener('touchstart',stop,{passive:true});track.addEventListener('touchend',schedule,{passive:true});schedule()}
 function updateStatus(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:D.timezone,weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const day=parts.find(x=>x.type==='weekday').value.toLowerCase(),time=parts.find(x=>x.type==='hour').value+':'+parts.find(x=>x.type==='minute').value,h=D.openingHours[day];const known=h&&h.open,open=known&&time>=h.open&&time<h.close;$('#openStatus').textContent=known?tr(open?'open':'closed'):tr('unknown');$('#todayHours').textContent=known?`${h.open} – ${h.close}`:'';$('.status').classList.toggle('is-open',open)}
 function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('shown');io.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(e=>io.observe(e));const sectionObserver=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('in-view',e.isIntersecting)),{threshold:.12,rootMargin:'-5% 0px -12%'});$$('.section').forEach(e=>sectionObserver.observe(e))}
 $('#langToggle').onclick=()=>{lang=lang==='ar'?'en':'ar';localStorage.setItem('alEnjazLang',lang);render()};$('#menu').onclick=()=>{const open=$('#header').classList.toggle('nav-open');$('#menu').setAttribute('aria-expanded',String(open))};$$('.nav a').forEach(a=>a.onclick=()=>$('#header').classList.remove('nav-open'));addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight,progress=max>0?scrollY/max:0;$('#header').classList.toggle('scrolled',scrollY>24);$('#mobileBar').classList.toggle('visible',scrollY>innerHeight*.65);$('#scrollProgress').style.transform=`scaleX(${progress})`;document.documentElement.style.setProperty('--page-scroll',String(Math.min(1,scrollY/innerHeight)));document.documentElement.style.setProperty('--ambient-y',`${-scrollY*.045}px`);document.documentElement.style.setProperty('--ambient-x',`${Math.sin(scrollY*.002)*24}px`)},{passive:true});
 async function launchSpeedometer(){const value=$('#speedValue'),gear=$('#gearValue'),needle=$('.hero-machine .needle'),hero=$('.hero');if(!value||!gear||!needle)return;const paint=speed=>{const safe=Math.min(220,Math.max(0,speed));value.textContent=String(Math.round(safe));needle.style.transform=`rotate(${-135+270*(safe/220)}deg)`},wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),animate=(from,to,duration,easing='accelerate')=>new Promise(resolve=>{const started=performance.now();const tick=now=>{const p=Math.min(1,(now-started)/duration),e=easing==='linear'?p:easing==='decelerate'?1-Math.pow(1-p,2):1-Math.pow(1-p,3);paint(from+(to-from)*e);if(p<1)requestAnimationFrame(tick);else resolve()};requestAnimationFrame(tick)});if(matchMedia('(prefers-reduced-motion: reduce)').matches){gear.textContent='1';paint(0);return}const stages=[{gear:1,from:0,to:58,duration:1550},{gear:2,from:58,to:44,duration:360,shift:true},{gear:2,from:44,to:101,duration:1450},{gear:3,from:101,to:85,duration:360,shift:true},{gear:3,from:85,to:146,duration:1450},{gear:4,from:146,to:127,duration:380,shift:true},{gear:4,from:127,to:188,duration:1450},{gear:5,from:188,to:168,duration:380,shift:true},{gear:5,from:168,to:220,duration:1850}];while(true){hero.classList.add('is-accelerating');for(const stage of stages){gear.textContent=String(stage.gear);hero.classList.toggle('is-shifting',!!stage.shift);await animate(stage.from,stage.to,stage.duration,stage.shift?'linear':'accelerate')}hero.classList.remove('is-shifting','is-accelerating');gear.textContent='5';paint(220);await wait(1400);await animate(220,0,3400,'decelerate');gear.textContent='1';paint(0);await wait(2200)}}
 function setupMotionDetails(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const hero=$('.hero');if(!hero.dataset.motionBound){hero.dataset.motionBound='true';hero.addEventListener('pointermove',e=>{if(innerWidth<900)return;const x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*8;hero.style.setProperty('--parallax-x',`${x}px`);hero.style.setProperty('--parallax-y',`${y}px`)});hero.addEventListener('pointerleave',()=>{hero.style.setProperty('--parallax-x','0px');hero.style.setProperty('--parallax-y','0px')})}$$('.service-card').forEach(card=>card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--spot-x',`${e.clientX-r.left}px`);card.style.setProperty('--spot-y',`${e.clientY-r.top}px`)}))}
 function setupLightbox(){const box=$('#lightbox');if(!box)return;$$('.gallery-item').forEach(item=>item.onclick=()=>{const img=$('img',box),thumb=$('img',item);img.src=item.dataset.full;img.alt=thumb.alt;box.showModal()});$('button',box).onclick=()=>box.close();box.onclick=e=>{if(e.target===box)box.close()}}
 $('#yearNow').textContent=new Date().getFullYear();render();setupLightbox();launchSpeedometer();setInterval(updateStatus,60000);
})();
